appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: GKhCR8QE3ZbJzhIGY6Yjb3fYhwdJUsCpv4JJ/90pN/LO4YvqqGZ8agUNPK183Ts6fKf7h7g/5ofN7iy+a2fdrhgzqq1bsGalnsgh4rFNlNmh6qqSbXM6ApIH0qqCzxhA/dm3xJEvaiSHSPgsJQCSZ20ZCWmhUgCyHfRKIFk0aZTlvtQ3Zwy6XbJ59VC27WSL4uxBD5qkMyc+QndAMDEfqUzrk5seIlTI+Np77U1G3MovUY+brkQwkJYTKHmp7avYkP2xhBGAlHyy0Zec12tz0cyrYBeduo78uO7+WM3F7Rzh/5d5krD5mnJ5cdWKPFBbEUpA9BNDk8mhXP1vKF258kihjXnzz2PnlZHsYjmvd+Agb7if4CvgiWaHhJSkbUti4GPgUjXUEfTvD9sxiA+vOG3/VQJ9jSf4LyyBs5Jb8fvLDzwA8IowFris7MHxG2Stvccet/WWwFmnqCJrm5tTIsH3GAzgt09pCr61kMC1FBP6jKTQjk29d/sMEeadhKqeTjR5AL7rvg46KdylLEq+un3HgKd2tEcrNWvwuO+v+tPicmuaAkanAX6PeYj4u2+mNs/w716+tPcnHWBlMk0h5CiowuD8H7639domZkdDLupbv0/t6alwQrU9V+77fssPOcEnrtf5Mrug66fJ6sqsh5WO3fQEmqiZETgDCRpziPU=
conda_forge_output_validation: true
