travis:
  secure:
    BINSTAR_TOKEN: DZDYjGpE+nEcWxMqDeHPhLU+KkDa2RWL+P6jDolZibgqPOCSaPDmTa2/3YWv4l9LZfhYGAO56gM1bMpOkJ20J1l7G6qPPxTY+S9V6NKfmwvO7ofgJ5SWKEsri0g5/zeILhlBj+/1+cIJG1wrsTJ6dlf5X7DAHqAHmmjj+CExvkNhwFR5rdE0wqE5yMRdypXhjMDji3Zvoq6PIqXXLDeyCwbKszuSkQ2kfW9VeIWuCOmyxRT8ZPpTSnXGbZ4Wb1KZSjY2ql8ewEn5ATYP0cEClLL6aJvm2gNHW/8ReojGj6jUTKGD7KSKH8oSRbeLHxmPgXsxKzWBtZ/nyW0dKsug+8G2/bqZYawj/J4+nyLWnFJv+V7JcOV6gaVfP3/TgtR+mvuJiRWHa9O7HVCJUcIhJY5zLlyWeI/rS4huyrFs1cbQOXxjqy7FfM9q/QLIxcwuqC1OHWkKFrtZX76igCewFuhjT4D+cK/v5QY/V/KuBCcHlsPlaaOsybfhx9nq1Oa3hX3LmYZo51KBz2bv2crPlE0JbdDABO3kSulTvLp6TERc5mYu3srsnLB0BcOTMqgLNBBLJ4r83pgmXeXmUvmrTqnRpxsX0xDKnZdqrx+DQCF8qb5LhHjwb7ixHXhaI+HVRvj5BsKbqWQMvikXqnpjvaLZa8gQiyhSJ5YbakcNyzg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
